4.13. Обратная сторона реальности
htmlacademy-react/1963109-six-cities-10 pull request #5
Opened 2022-08-02 13:48 UTC by Laskoviy

2022-08-03 09:11 UTC, DmitryMarkov requested changes
Есть замечания по качеству кода

2022-08-03 09:11 UTC, DmitryMarkov commented on project/src/components/favorite-offer-list/favorites-offer-list.tsx
> +import FavoriteCity from '../fav-city/fav-city';
сокращения запрещены. Название файлы = название класса

2022-08-03 09:11 UTC, DmitryMarkov commented on project/src/components/favorite-offer-list/favorites-offer-list.tsx
> +    <Fragment>
Можно просто

```suggestion
    <>
```

2022-08-03 09:11 UTC, DmitryMarkov commented on project/src/components/property-picture/property-picture.tsx
> +        alt="Studio"
по идее это тип проперти и тогда он должен передаваться в компонент

2022-08-03 09:11 UTC, DmitryMarkov commented on project/src/components/user-review/user-review.tsx
> +function UserReview({ reviews }: UserReviewProps): JSX.Element {
Название компонента подразумевает что у тебя один отзыв, а у тебя список - это плохо, надо исправить

2022-08-03 09:11 UTC, DmitryMarkov commented on project/src/components/offers-list/offers-list.tsx
> +function OffersList({ offers, cardClass }: Props): JSX.Element {
Можно просто Offers

2022-08-03 09:11 UTC, DmitryMarkov commented on project/src/components/user-review/user-review.tsx
> +          < li
пробелов тут быть не должно, посмотри настройки линтера. он должен такое находить

```suggestion
          <li
```

2022-08-03 09:11 UTC, DmitryMarkov commented on project/src/components/utils/utils.ts
> +  return text.charAt(FIRST_LETTER).toUpperCase() + text.slice(START_INDEX);
по критериям да, правильно выносить магические значения в константы, но тут я бы не стал, потому что довольно очевидно из контекста

2022-08-03 09:11 UTC, DmitryMarkov commented on project/src/const.ts
> +export const ImageSize = {
если это используется только в одном файле (компоненте), нет смысла выносить в константы проекта, иначе тут их будут тысячи. оставь только переиспользуемые

2022-08-03 09:11 UTC, DmitryMarkov commented on project/src/types/offer.ts
> +  location: Location;
в больших списках ключей их лучше сортировать по алфавиту, чтобы было проще искать и читать код. понятно, что это моки и они уйдут, но в будущем постарайся это учитывать

2022-08-04 10:43 UTC, Laskoviy commented on project/src/components/app/card/card.tsx
> +  onInactive?: () => void;
Может тогда пока их удалить?

2022-08-04 10:43 UTC, Laskoviy commented on project/src/components/bookmark-button/bookmark-button.tsx
> +  }
не понимаю как это реализовать... Можете подробнее рассказать?

2022-08-04 10:45 UTC, Laskoviy commented on project/src/components/favorite-offer-list/favorites-offer-list.tsx
> +    <Fragment>
Я так понял во всех файлах <Fragment>...</Fragment> заменить на <>...</>

2022-08-04 10:46 UTC, Laskoviy commented on project/src/components/property-picture/property-picture.tsx
> +        alt="Studio"
тоже не понял что вы имеете ввиду(

2022-08-04 10:47 UTC, Laskoviy commented on project/src/components/offers-list/offers-list.tsx
> +function OffersList({ offers, cardClass }: Props): JSX.Element {
не получится так назвать функциональный компонент так как есть тип с таким названием и будет конфликт

2022-08-05 11:41 UTC, DmitryMarkov commented on project/src/components/offers-list/offers-list.tsx
> +function OffersList({ offers, cardClass }: Props): JSX.Element {
Хорошо, тогда оставляем

2022-08-05 11:41 UTC, DmitryMarkov commented on project/src/components/app/card/card.tsx
> +  onInactive?: () => void;
Можно сделать обязательными

2022-08-05 11:42 UTC, DmitryMarkov commented on project/src/components/bookmark-button/bookmark-button.tsx
> +  }
Так же как в предыдущем комменте, где onActive, но можно оставить на следующий раз где будет имплементация, раз пока не понятно

2022-08-05 11:43 UTC, DmitryMarkov commented on project/src/components/favorite-offer-list/favorites-offer-list.tsx
> +    <Fragment>
Да, можно

2022-08-05 11:44 UTC, DmitryMarkov commented on project/src/components/property-picture/property-picture.tsx
> +        alt="Studio"
Ну, там текстом написано Studio, но не все прлперти студии, есть ещё дома, апартаменты... Эти данные есть в моках, откуда их и можно взять. Так?

2022-08-08 11:17 UTC, DmitryMarkov approved these changes
Замечания приняты, задание выполнено

2022-08-08 11:17 UTC, merged